[package]
rust-version.workspace = true
name = "sdkwork-api-rtc-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-rtc application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_rtc_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
anyhow = "1.0.98"
serde_json.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-communication-rtc-repository-sqlx.workspace = true
sdkwork-communication-rtc-service.workspace = true
sdkwork-rtc-service-host.workspace = true
sdkwork-rtc-plugin-bootstrap.workspace = true
sdkwork-routes-rtc-app-api.workspace = true
sdkwork-routes-rtc-backend-api.workspace = true
