[package]
rust-version.workspace = true
name = "sdkwork-communication-rtc-worker"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-rtc-service-host.workspace = true

[dev-dependencies]
tokio.workspace = true

[lib]
path = "src/lib.rs"
