[package]
rust-version.workspace = true
name = "sdkwork-communication-rtc-repository-sqlx"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-rtc-database-host.workspace = true
sdkwork-database-config.workspace = true
sdkwork-database-repository.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-communication-rtc-service.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true

[dev-dependencies]
tokio.workspace = true
