[package]
rust-version.workspace = true
name = "sdkwork-routes-rtc-backend-api"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"


[lints]
workspace = true
[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-rtc-app-context.workspace = true
sdkwork-communication-rtc-service.workspace = true
sdkwork-utils-rust.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-web-contract.workspace = true
sdkwork-web-core.workspace = true

[build-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tokio.workspace = true
tower.workspace = true
