[package]
rust-version.workspace = true
name = "sdkwork-rtc-service-host"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-communication-rtc-service.workspace = true
sdkwork-drive-storage-contract.workspace = true
sdkwork-drive-workspace-service.workspace = true
sdkwork-routes-rtc-app-api.workspace = true
sdkwork-routes-rtc-backend-api.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
sdkwork-drive-config.workspace = true
sdkwork-drive-storage-local.workspace = true
sqlx.workspace = true
tokio.workspace = true
