[package]
rust-version.workspace = true
name = "sdkwork-rtc-adapter-agora"
edition.workspace = true
license.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-communication-rtc-service.workspace = true
sdkwork-utils-rust.workspace = true
serde_json.workspace = true
hmac = "0.12.1"
sha2 = "0.10"
